baseURL = "https://avionapedales.org/"
languageCode = "fr"
title = "Avion a Pedales"
theme = ""

[params]
  bio = "üéØ Faire des randos v√©lo dans le ciel"
  description = "Je construis un v√©hicule hybride entre v√©lo electrique et ULM. Je le souhaite sobre, low-tech et contemplatif."
  instagram = "https://www.instagram.com/avionapedales/"
  patreon = "https://www.patreon.com/alixcool"
  youtube = ""
  videoEmbed = "https://www.youtube.com/embed/72-GKUz-6ZY?rel=0"
  model3d = ""
  statusDate = "Juillet 2025"
  statusText = "Le banc d'essai V2 a atteint une poussee suffisante pour le d√©collage. Prochaine √©tape : construction des ailes."

[params.links]
  [params.links.patreon]
    title = "Soutenir le projet"
    url = "https://www.patreon.com/alixcool"
    icon = "heart"
  [params.links.job]
    title = "Recrute associ√©.e m√©cano"
    url = "https://jobs.makesense.org/fr/jobs/avion-a-pedales-associee-mecano-avion-a-pedales-d0tInv6bzBmYiOM7Jy4r"
    icon = "wrench"
  [params.links.video]
    title = "Le projet en 2 minutes"
    url = "#"
    icon = "play"
  [params.links.model]
    title = "Mod√®le 3D (v0.1)"
    url = "https://gmail1680791.autodesk360.com/g/shares/SH286ddQT78850c0d8a42219621574419ef1"
    icon = "cube"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML"]

[pagination]
  pagerSize = 10
